theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

lang: EN

title: Eric Patrizio
description: Software craftsman, agile and open source enthusiast. In continuous learning ;)

meta_title: Software craftsman, agile advocate | Eric Patrizio
meta_description: Software craftsmanship, agility and open source enthusiast. I'm in continuous learning ;)
meta_keywords: software, craft, craftsman, craftsmanship, agile, agility, clean code, programming, open source

github_link: https://github.com/epatrizio
linkedin_link: https://www.linkedin.com/in/eric-patrizio-215832
twitter_link: https://twitter.com/EricPatrizio
