theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

lang: EN

title: Eric Patrizio
description: R&D software engineer. Programming languages design enthusiast.

meta_title: R&D software engineer, software craftsman | Eric Patrizio
meta_description: R&D software engineer, software craftsman, passionate about internal understanding of programming languages. Agile and open source advocate.
meta_keywords: software engineer, software craftsman, software craftsmanship, agile, programming languages, open source

github_link: https://github.com/epatrizio
linkedin_link: https://www.linkedin.com/in/eric-patrizio-215832
