theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

lang: EN

title: Eric Patrizio
description: Software craftsman, Internal understanding programming languages enthusiast.

meta_title: Software craftsman, programming languages engineer | Eric Patrizio
meta_description: Software craftsman, passionate about internal understanding of programming languages. Agile and open source advocate.
meta_keywords: software craftsman, software craftsmanship, agile, agility, clean code, programming languages, open source

github_link: https://github.com/epatrizio
linkedin_link: https://www.linkedin.com/in/eric-patrizio-215832
twitter_link: https://twitter.com/EricPatrizio
